# Generated by Django 5.0.3 on 2026-07-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0004_cancion_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='bpm',
            field=models.FloatField(blank=True, null=True, verbose_name='Tempo (BPM)'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='brillo_ia',
            field=models.FloatField(blank=True, null=True, verbose_name='Brillo IA (Hz)'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='energia_ia',
            field=models.FloatField(blank=True, null=True, verbose_name='Energía IA'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='genero_ia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Género IA'),
        ),
    ]
