# Generated by Django 5.0.3 on 2026-07-15 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0005_cancion_bpm_cancion_brillo_ia_cancion_energia_ia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='es_plagio',
            field=models.BooleanField(default=False, verbose_name='Sospecha de Plagio'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='plagio_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sospechas_plagio', to='musica.cancion', verbose_name='Plagio de'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='similitud_plagio',
            field=models.FloatField(blank=True, null=True, verbose_name='Similitud de Plagio (%)'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='vector_timbre',
            field=models.JSONField(blank=True, null=True, verbose_name='Vector de Timbre (MFCC)'),
        ),
    ]
