services:
  - type: web
    name: misterticket-backend
    runtime: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate --noinput &&
      python manage.py seed_admin &&
      python manage.py seeder_eventos &&
      python manage.py seeder_add_artistas
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.4"
      - key: USE_S3
        value: "False"
      - key: LIBELULA_API_KEY
        sync: false
      - key: BACKEND_BASE_URL
        sync: false