# Generated by Django 5.0.3 on 2026-06-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_factura_codigo_transaccion_pasarela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado_pago',
            field=models.CharField(default='pendiente', help_text='pendiente, pagado, reembolsado, cancelado, cancelada', max_length=50, verbose_name='Estado del pago'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(default='activo', help_text='reservado, activo, usado, cancelado, expirado', max_length=50, verbose_name='Estado'),
        ),
    ]
